#!/usr/bin/env node
/**
 * Reads all *.svg files in src/components/icons/ and generates index.tsx
 * — a React component per icon, plus a combined barrel export.
 *
 * Run whenever new icons are added:  node scripts/build-icons.mjs
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ICON_DIR = join(__dirname, "..", "src", "components", "icons");

// kebab-case → PascalCase
function toPascal(name) {
  return name
    .split("-")
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
}

// Convert SVG attribute names to React camelCase
function toReactAttrs(svg) {
  return svg
    .replace(/stroke-width=/g, "strokeWidth=")
    .replace(/stroke-linecap=/g, "strokeLinecap=")
    .replace(/stroke-linejoin=/g, "strokeLinejoin=")
    .replace(/stroke-miterlimit=/g, "strokeMiterlimit=")
    .replace(/stroke-dasharray=/g, "strokeDasharray=")
    .replace(/stroke-dashoffset=/g, "strokeDashoffset=")
    .replace(/fill-rule=/g, "fillRule=")
    .replace(/clip-rule=/g, "clipRule=")
    .replace(/clip-path=/g, "clipPath=")
    .replace(/xmlns:xlink=/g, "xmlnsXlink=")
    .replace(/xlink:href=/g, "xlinkHref=");
}

const files = readdirSync(ICON_DIR)
  .filter((f) => f.endsWith(".svg"))
  .sort();

const components = files.map((file) => {
  const name = file.replace(/\.svg$/, "");
  const componentName = toPascal(name) + "Icon";
  let svg = readFileSync(join(ICON_DIR, file), "utf8").trim();
  svg = toReactAttrs(svg);
  // Inject {...props} into root <svg> tag so callers can pass className, style, etc.
  svg = svg.replace(/<svg([^>]*)>/, "<svg$1 {...props}>");
  return { name, componentName, svg };
});

const body = `// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
// Re-run \`node scripts/build-icons.mjs\` after adding or updating SVGs.
import type { SVGProps } from "react";

${components
  .map(
    ({ componentName, svg }) =>
      `export function ${componentName}(props: SVGProps<SVGSVGElement>) {\n  return (\n    ${svg}\n  );\n}\n`,
  )
  .join("\n")}
export const iconNames = [
${components.map(({ name }) => `  "${name}",`).join("\n")}
] as const;

export type IconName = (typeof iconNames)[number];
`;

writeFileSync(join(ICON_DIR, "index.tsx"), body);
console.log(`Generated ${components.length} icon components in index.tsx`);
